configure: basic option parsing

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,16 @@
 #!/bin/sh
 
+set -e
+
+error() {
+  echo >&2 "$0: error: $@"
+}
+
+fatal_error() {
+  error "$@"
+  exit 1
+}
+
 show_usage() {
 cat <<EOT
 Usage: $0 [OPTION]... [VAR=VALUE]...
@@ -45,4 +56,115 @@ Report bugs to <frank-vlock@benkstein.net>.
 EOT
 }
 
-show_usage
+enable_feature() {
+  case "$1" in
+    plugins)
+      enable_plugins="$2"
+    ;;
+    root-password)
+      enable_root_password="$2"
+    ;;
+    pam|shadow)
+      if [ "$2" = "yes" ] ; then
+        if [ -n "$auth_method" ] && [ "$auth_method" != "$1" ] ; then
+          fatal_error "pam and shadow authentication are mutually exclusive"
+        fi
+        auth_method="$1"
+      else
+        fatal_error "cannot disable authentication"
+      fi
+    ;;
+    *)
+      fatal_error "invalid feature name: $1"
+    ;;
+  esac
+}
+
+while [ $# -gt 0 ] ; do
+  opt=`expr "x$1" : 'x\([^=]*\)=.*' ||:`
+  optarg=`expr "x$1" : 'x[^=]*=\(.*\)' ||:`
+  case "$1" in
+    --disable-*)
+      feature=`expr "$1" : '--disable-\(.*\)'`
+      enable_feature "$feature" no
+      shift
+    ;;
+    --enable-*=no)
+      feature=`expr "$1" : '--enable-\(.*\)=no'`
+      enable_feature "$feature" no
+      shift
+    ;;
+    --enable-*=yes)
+      feature=`expr "$1" : '--enable-\(.*\)=yes'`
+      enable_feature "$feature" yes
+      shift
+    ;;
+    --enable-*)
+      feature=`expr "$1" : '--enable-\(.*\)'`
+      enable_feature "$feature" yes
+      shift
+    ;;
+    --*=*)
+      shift
+      # unshift
+      eval set -- "$opt" "$optarg" "$@"
+    ;;
+    --prefix)
+      prefix="$2"
+      shift 2 || fatal_error "$1 argument missing"
+    ;;
+    --bindir)
+      bindir="$2"
+      shift 2 || fatal_error "$1 argument missing"
+    ;;
+    --sbindir)
+      sbindir="$2"
+      shift 2 || fatal_error "$1 argument missing"
+    ;;
+    --libdir)
+      libdir="$2"
+      shift 2 || fatal_error "$1 argument missing"
+    ;;
+    --moduledir)
+      moduledir="$2"
+      shift 2 || fatal_error "$1 argument missing"
+    ;;
+    --scriptdir)
+      scriptdir="$2"
+      shift 2 || fatal_error "$1 argument missing"
+    ;;
+    --mandir)
+      mandir="$2"
+      shift 2 || fatal_error "$1 argument missing"
+    ;;
+    --help)
+      show_usage
+      exit
+    ;;
+    --*)
+      error "unrecognized option: $1"
+      echo >&2 "Try \`$0 --help' for more information."
+      exit 1
+    ;;
+    *)
+      fatal_error "invalid argument: $1"
+    ;;
+  esac
+done
+
+cat <<EOF
+vlock configuration"
+
+directories:
+  prefix:     $PREFIX
+  bindir:     $BINDIR
+  sbindir:    $SBINDIR
+  libdir:     $LIBDIR
+  scriptdir:  $SCRIPTDIR
+  moduledir:  $MODULEDIR
+
+features:
+  plugins:        $ENABLE_PLUGINS
+  root-password:  $ENABLE_ROOT_PASSWORD
+  auth-method:    $AUTH_METHOD
+EOF
